c({"name": "g.errorCatcher.handleCatchException", "params": {"caughtException": {"description": "<p>The caught JS exception.</p>", "type": "Error", "optional": false, "order": 0, "name": "caughtException"}, "context": {"description": "", "type": "", "optional": false, "order": 1, "name": "context"}}, "ret": {"type": "undefined", "description": ""}, "type": "function", "comment": "<p>Handles a caught exception. When window.onerror is available, the exception is re-thrown so that additional\ninformation from window.onerror can be added. Otherwise, the exception is passed to reportException, where it is\nsent to GEC and potentially displayed to the user.</p>", "src": "appDev/node_modules/socket.io/node_modules/socket.io-client/node_modules/uglify-js/tmp/app.js", "line": 13494, "children": []})